### ISSUE TITLE
#2 Build Random Forest Algorithm from scratch 

### ISSUE THREAD

**Issue by prasanna-muppidwar** [prasanna-muppidwar/AlgoKit#2]
Hey! Task is to build a random forest algorithm which supports classification type of problems with simple python and Numpy! Keep the code clean and readable also don't forget to add testcases! 

#hacktoberfest24

**Comment by Nithin-Chakravarthi** [comment]
Hey @prasanna-muppidwar, I would like to contribute to build a random forest algorithm, Hope you can assign me the task.

**Comment by prasanna-muppidwar** [comment]
Hey @Nithin-Chakravarthi I have assigned it to you! Don't forget to add test cases! Waiting for your pr!

**Comment by prasanna-muppidwar** [comment]
Thank You @Nithin-Chakravarthi for your contribution! You can check other issues as well!
